### ISSUE TITLE
update with the most recent code from fusion

### ISSUE THREAD

**Issue by sethherr** [ErgoDox-EZ/fusion-rails#3]
I spent some time working on things, didn't realize there was a much better version live that isn't in the repository.

Where is the code from http://rocketcode.nl/fusion/ ?

I'd like to contribute, but now I feel like I wasted my time and your time.

**Comment by ezuk** [comment]
Hi Seth,

You did not waste your time at all. This _is_ the latest code. If you look at the org - https://github.com/ErgoDox-EZ - you'll see the old Fusion repo (last updated 23 days ago), and this, fusion-rails, which is much more active.

It may seem like a step back, but that's only because this is a full-blown Rails app rather than just the client-side part, which is what Fusion has.

@tdegrunt - to avoid confusion, do you think we could kill the fusion repo in the org? Or do you still need any of the code there?

**Comment by tdegrunt** [comment]
The code from the site is outdated, we've switched to reactjs in the meantime, it's much more maintainable than the old code.

I'll try and remove this repo and put it in the fusion repo instead.
